apiVersion: v1
kind: Namespace
metadata:
  name: nginx-1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-1-tls-cert
  namespace: nginx-1
spec:
  secretName: nginx-1-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "nginx.pimonlab.xyz"
  dnsNames:
  - "nginx.pimonlab.xyz"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
  namespace: nginx-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests: # "I need at least this much..."
            cpu: "100m"    # 10% of a CPU core
            memory: "128Mi" # 128 Mebibytes of memory
          limits: # "Don't let me use more than this much..."
            cpu: "110m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
  namespace: nginx-1
spec:
  type: ClusterIP
  selector:
    app: nginx-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-1
  namespace: nginx-1
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nginx.pimonlab.xyz`)
      priority: 10
      services:
        - name: nginx-1
          port: 80
    - kind: Rule
      match: Host(`nginx.pimonlab.xyz`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: nginx-1
          port: 80
          scheme: h2c
  tls:
    secretName: nginx-1-ts-secret
