apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seer-1
  namespace: seer-1
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`seer.pimonlab.xyz`)
      priority: 10
      services:
        - name: seer-1-seerr-chart
          namespace: seer-1
          port: 5000
  tls:
    secretName: seer-1-ts-secret
