apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # 1. Node Exporter (Hardware Metrics: CPU, RAM, Disk)
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      targetRevision: 4.23.0  # Use latest version suitable
      helm:
        values: |
          service:
            type: NodePort
            nodePort: 31000  # Fixed port so we know where to scrape
            port: 9100

    # 2. Kube State Metrics (Pod Metadata: Crashes, Restarts, Status)
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      targetRevision: 5.16.0 # Use latest version suitable
      helm:
        values: |
          service:
            type: NodePort
            nodePort: 31001  # Fixed port so we know where to scrape