apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-agent
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.27.0
    helm:
      values: |
        # DISABLE EVERYTHING WE DON'T NEED
        server:
          enabled: false
        pushgateway:
          enabled: false
        alertmanager:
          enabled: false

        # ENABLE ONLY THE AGENT
        agent:
          enabled: true
          # STRICT RAM LIMITS FOR 2GB NODES
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
          
          remoteWrite:
            - url: "http://192.168.6.15:8428/api/v1/write"
          
          externalLabels:
            cluster: 'my-k3s-cluster'

        # KEEP THE EXPORTERS LIGHT
        prometheus-node-exporter:
          enabled: true
          resources:
            limits:
              memory: "50Mi"
        
        kube-state-metrics:
          enabled: true
          resources:
            limits:
              memory: "100Mi"