apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-services-1
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://github.com/pimonteiro/Mimisbrunnr-k8s.git'
      targetRevision: HEAD
      path: external-services-routing