apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance-1
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/felixZmn/glance.git'
      targetRevision: 1.0.0
      path: .
      helm:
        values: |
          ingress:
            enabled: false

    - repoURL: 'https://github.com/pimonteiro/Mimisbrunnr-k8s.git'
      targetRevision: HEAD
      path: glance-1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: glance-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true