apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glance-1

configMapGenerator:
  - name: glance-1
    files:
      - config.yaml=dashboard/config.yaml

generatorOptions:
  disableNameSuffixHash: true
