apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warracker-1-db-pvc
  namespace: wwarracker-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warracker-1-uploads-pvc
  namespace: warracker-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi