apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pdf-starling-1-tls-cert
  namespace: pdf-starling-1
spec:
  secretName: pdf-starling-1-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "pdf-editor.pimonlab.xyz"
  dnsNames:
  - "pdf-editor.pimonlab.xyz"
