apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-starling-1-configs-pvc
  namespace: pdf-starling-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 2Gi
