---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr-1
  namespace: suwayomi-server-1
spec:
  selector:
    matchLabels:
      app: flaresolverr-1
  template:
    metadata:
      labels:
        app: flaresolverr-1
    spec:
      containers:
      - name: flaresolverr-1
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
        - containerPort: 8191
        env:
        - name: TZ
          value: "Europe/Lisbon"
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-1
  namespace: suwayomi-server-1
spec:
  selector:
    app: flaresolverr-1
  ports:
  - port: 8191
    targetPort: 8191