apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-server-1-downloads-pvc
  namespace: suwayomi-server-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # This tells k3s to use Longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-server-1data-pvc
  namespace: suwayomi-server-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
