apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-1
  namespace: speedtest-tracker-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker-1
  namespace: speedtest-tracker-1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: speedtest-tracker-1
  template:
    metadata:
      labels:
        app: speedtest-tracker-1
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 172.16.16.5
          - 8.8.8.8
        searches:
          - speedtest-tracker-1.svc.cluster.local
        options:
          - name: ndots
            value: "5"
      containers:
        - name: speedtest-tracker-1
          image: lscr.io/linuxserver/speedtest-tracker:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "400m"
            requests:
              memory: 256Mi
              cpu: "200m"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: DISPLAY_TIMEZONE
              value: UTC
            - name: DB_CONNECTION
              value: sqlite
            - name: SPEEDTEST_SCHEDULE
              value: 0 * * * *
            - name: SPEEDTEST_SERVERS
              value: 47363,10363
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: speedtest-tracker-1-password
                  key: app_key

          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker-1
      volumes:
        - name: speedtest-tracker-1
          persistentVolumeClaim:
            claimName: speedtest-tracker-1
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker-1
  namespace: speedtest-tracker-1
spec:
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: speedtest-tracker-1
