apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: planka
  namespace: planka-1
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`planka.pimonlab.xyz`)
      priority: 10
      services:
        - name: planka
          namespace: planka
          port: 80
  tls:
    secretName: planka-tls-secret
