---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-1-oidc-auth
  namespace: glance-1
spec:
  encryptedData:
    clientId: AgCsdEf1xV7/oMBssamGOgnt9phYlbLzLySpNan6hlW6AS3+gVWf8PIx9JcKiSckFJk+kdCxflfLPVY8oYODXvDCqnKH43N3WZPA0VPsqp1LRxHm4UVaZRIoQv+pvt6OY/bdFpNhfUC7MtTBqWTcAC0v5r/gHXWnaUp9CcYEBx1et8/teUkKqfCO4Jd3/txvgM26DcmC39vk8eSmwMzynTO5suTDzTfA8YBzoqJew6Yl8JCzmMFxTBymcQ9Fb/AfJ2bIXUmaEpFIuNy0f0nEOCV2XE9uQhfRF4wSaNfcpoB1Dtzy2v4bzxXAMc13TPWDtS3serST3a2HZ5TljhkhuVOJjvLtcwzBkcMLH7IiFUTBiT/VL7UV8loyUSbb9qdpvrdTcBSxr9pWwNjttnAmql6f+qmbxL4G8y+tv2t6X361Xk6VVOyazZb6/hVUCFT1C9Tj6iaQXMwO7REK0JlGpSocT6TvhGV2Bsa8Sd6WKcF0h5P/wR8FdosZtivav+UmAj3fL0qnovJEFdpdNTB8L9E29Pw5zd4Ti4k2YMGj1tf1m7qJoctMJZqwbzrXmcKBymtdPj4tfWBLWr2ITperjb74GxmuYHaXiCirj3t/U4rmGmOIfn5Re8DZuSS896ZUWN4iyy7iwg6ES7EbjFj0s6ZI8gJmmUZy9yrDkQ2HLuWGYiHHV0pFKdewzNzY0nPmtQpc7Refy8L62p3BbRYXjlmJWAz+qFVnV9csYbK61WCrVine1fGao5PV
    clientSecret: AgBZPAN0xZgrpt9YLo8LrFL1QLue4tOBUSEMP3E1aWLq+D3gnRRkLqyVEhoW8axio3fn2QSt9eqv5Ub2LY4iaNVy55RI2cIS5uSgyUTeyIQ/hbeoO463L+aaPYwlYkHBrUlRKGY9PHQMyUMTx463TQwIcPUPU6RtMHCJorp+m5Hl0wOEwpvYR7hQpXa1kW5j/k13NZ5qcxZHQ63LCVBECF5h6LPqBYHDpQoTW9rTWd41FSIoQmnDEgJ0+q9v9zxzqZNkriTqRodRf/5/BihrnVbfp6WPHrHtYFBLNr6VFp8CBqJJzsc9kHJU+txeB1WRdzTwm35TC3dUxxTTWX5YYC8oZd6/RSGFIVTSUSC7gWfnjyf1QFyjqZohNg6zIEKaw7/zIPR2Ji2Crkmy6wAC8mwnr3/mSgZ28+/OlecJizbgUTnO2zZz/mClSs3YL/4qt81zmsqbOxUC2dtA9/WJsMvW9ogsjo535MPZaLb4vB/VnuoYd7Vxb+DqD3b14tMHYmsksqy7LitlGEys/CXEF6nn4Y/AjHKvkkJ4D/E5r6tU5qN0DDuk3dpn4au1BPY8VX8TsGImCbv1wh+QiC8aEic5rGmiy56pArFUtBjo+eA/aRYHP25Ueursbb1kJn2R9GfPzVVDFOUc3rdOK+oyYFXc4WsOXnX0PxtsoPuAojzWLhycW4ozPNmLtY+yE4E2lq4Efk01ALw3PkWAq02zybBcx/CH04lJUTOJgJS0ikGPvAodZOsfPsoi+xyLB+YWr6qUBlv6RiECnZBnsbTZIl0G1Oty2BbwLXGGvwhKIfq3k9IIx5bbstlQRyMHqm3bgVM5N/e9l7ypU5WoXiNnYu73KPmUezkJWFQwB7xGlBEF6w==
  template:
    metadata:
      annotations:
        reloader.stakater.com/match: "true"
      name: planka-1-oidc-auth
      namespace: glance-1
    type: Opaque
