---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-1-oidc-auth
  namespace: planka-1
spec:
  encryptedData:
    clientId: AgBrTYOS0y3Eu/KDB0g52hX33AH9l+TcRlSBp5naG43eH+H7S5DH3j5Tw3T/GhfA13DaBjSx7FiLTMmxs/HQzmlkFY4CPq+mtf+JtvGFu1CA404/36O+UHd9jCIfuG32ITjLYIHeIPY55OtLQX0OFyZ5EZmeRwarNZsk3xp6vnAvl9gLkcOd5IVjSexyl4AWo65e19sDLKvmAMTuZ4UxxMGGVkj9j4zMzz63erltAuiuTRwPH54e4ZJv16w3ebXhCRqw0JL96ui28JMxVfjYlhjt+ugm/9qOvSOGNgRnCsg1Zm3WwghPhDrF0TlfpSYr2Sd/hJxpGqUM0fZ1RqwsxisPl7mDv4f7PhHyjGcm6b9VQixj5orP2esJblUvvo/MAl0NmLVrkMz7zeKMeXXGvWbHysODjj1OjrlnGWM6DI2ibOxLJQ+Ec9PQZDVhm4brm0gRns88N8hDAwVBBBNz6qiiklQkEgTRGCYFvoKwmoaL4dHcZxQ/AFpGOzBkRqgOonajLRcGGciPs7/tAsEdxjhyTNzdwIIzFyVvEgBx50UztxRKEz0Vi6Pk2IqauYOgW+71bkoYKs59M75dKLQhGne0/6lyjvb68fzm9Onm+dbMkvuZhmqXMzLTFGSx2anGXKL8bbiIIlFWZ5qJyTniRxU7R7BldmtGK+cL+gYVNtn0wofs8lSRpBKCH38nNSNr22a3yqwCtypYvJOiEfKzxh2g03ZYhT0DVrnJKMvGyVnkdmD4m7mbEUHz
    clientSecret: AgCAPpqnlvYhfeHcM5QTksC0PwAGwANM3cD8yNHapCgRG3/W4SNqeYYvvakAvw3Iva/ybMEXq+7/Oy4avVnnb7SsmlUm3DR1eOJ6SBeCi4IEdDzh6wE6HAVSBYPKzXb3aaZRJBl03yn1M/d+J04V9/ivNbgSCxASOLGWa6gCgc5BWmlATR9MwJJWoxfaPCjwXi3/9PKZ6vT26SygNhVcm3qiRcxo8oiMrgF2TqBgkrcTCdByEBocg+Vq7X563gYsBHC02jm5zsvOVwOvRHUwn5nvLBkIp7fTI2Fj+lfgDLX9pNja7kYWJDhAB1yjfWYvcRwr3PqBjabCY0+LsVoLux20G+CFTcjhEa1jHqsdpVlrOpI5FlaFLdBRS1yNQ/Ub+RCPEccoZASH9AneBhzMAA98JEEMxa4LI3UeD6CUc9LyYwzdsEY7qnGHs1RZrB1rbMXUOKNirBDc1Ceu6EwRbgW1pv9rixDA2drz9PnVoTc8nnh0aFd+yHR9cvfoxBPxstQUzaKXYpqmVHVNOAzGVbLaJFY6LckvwpLgVCtR21bRR07CSNIbebcN25189pvPdYZlPGTopxhhknjBN8i1ZU3LunQhAXu0zRIMUjsJ+wegch0/ChcqIof34vVl0pgyMCs58FKG0VSTSwDVfh9gYLB7EDUWzvgmTH8yYYlAc9Rs8loqncYEX9qUGr3A/1HdqmTOMp/AxIlfHoYgTRJzpgAh4kDmbQKGZOF3lWpQHrVgjxh9Su4JwzBIZ3Eoglg6DJiyG3YcpEe5iWYMBjtcEV1wGOhqdBvy23eUW/P1IoCqRitfB+DsQEfwxzxYG3XoCQegIhUIAwSoV+mKp6YCoHmtLawUikanpZShPJSwV8ibbg==
  template:
    metadata:
      annotations:
        reloader.stakater.com/match: "true"
      name: planka-1-oidc-auth
      namespace: planka-1
    type: Opaque
