all:
  children:
    workers:
      hosts:
        k3s-01:
          ansible_host: 192.168.7.10
          ansible_user: ubuntu
        k3s-03:
          ansible_host: 192.168.7.13
          ansible_user: ubuntu
        k3s-04:
          ansible_host: 192.168.7.14
          ansible_user: ubuntu
        k3s-05:
          ansible_host: 192.168.7.16
          ansible_user: ubuntu
        k3s-06:
          ansible_host: 192.168.7.17
          ansible_user: ubuntu
        k3s-longhorn-01:
          ansible_host: 192.168.7.19
          ansible_user: ubuntu
        k3s-longhorn-02:
          ansible_host: 192.168.7.20
          ansible_user: ubuntu
        k3s-longhorn-03:
          ansible_host: 192.168.7.21
          ansible_user: ubuntu
    masters:
      hosts:
        k3s-m01:
          ansible_host: 192.168.7.12
          ansible_user: ubuntu
        k3s-m02:
          ansible_host: 192.168.7.15
          ansible_user: ubuntu
        k3s-m03:
          ansible_host: 192.168.7.18  # 49???
          ansible_user: ubuntu
