apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 13378
      targetPort: 13378
  selector:
    app: audiobookshelf-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf-proxy
  template:
    metadata:
      labels:
        app: audiobookshelf-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        # Listen on 13378 inside the pod, forward to 192.168.3.2:13378
        args: ["TCP-LISTEN:13378,fork", "TCP:192.168.3.2:13378"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            cpu: "10m"
            memory: "50Mi"
        ports:
        - containerPort: 13378
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audiobookshelf-tls-cert
  namespace: external-services
spec:
  secretName: audiobookshelf-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "audiobookshelf.pimonlab.xyz"
  dnsNames:
  - "audiobookshelf.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: audiobookshelf-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`audiobookshelf.pimonlab.xyz`)
      kind: Rule
      services:
        - name: audiobookshelf-svc
          port: 13378
  tls:
    secretName: audiobookshelf-ts-secret