apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-proxy
  template:
    metadata:
      labels:
        app: influxdb-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        args: ["TCP-LISTEN:8086,fork", "TCP:192.168.6.13:8086"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            memory: "50Mi"
        ports:
        - containerPort: 8086
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb-tls-cert
  namespace: external-services
spec:
  secretName: influxdb-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "influxdb.pimonlab.xyz"
  dnsNames:
  - "influxdb.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`influxdb.pimonlab.xyz`)
      kind: Rule
      services:
        - name: influxdb-svc
          port: 8086
  tls:
    secretName: influxdb-ts-secret
