apiVersion: v1
kind: Service
metadata:
  name: odin-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 8006
      targetPort: 8006
  selector:
    app: odin-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odin-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odin-proxy
  template:
    metadata:
      labels:
        app: odin-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        args: ["TCP-LISTEN:8006,fork", "TCP:172.16.16.10:8006"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            memory: "50Mi"
        ports:
        - containerPort: 8006
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: odin-tls-cert
  namespace: external-services
spec:
  secretName: odin-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "odin.pimonlab.xyz"
  dnsNames:
  - "odin.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: odin-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`odin.pimonlab.xyz`)
      kind: Rule
      services:
        - name: odin-svc
          port: 8006
  tls:
    secretName: odin-ts-secret
