apiVersion: v1
kind: Service
metadata:
  name: opnsense-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 443
      targetPort: 443
  selector:
    app: opnsense-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opnsense-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opnsense-proxy
  template:
    metadata:
      labels:
        app: opnsense-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        args: ["TCP-LISTEN:443,fork", "TCP:172.16.16.1:443"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            memory: "50Mi"
        ports:
        - containerPort: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opnsense-tls-cert
  namespace: external-services
spec:
  secretName: opnsense-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "opnsense.pimonlab.xyz"
  dnsNames:
  - "opnsense.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: opnsense-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`opnsense.pimonlab.xyz`)
      kind: Rule
      services:
        - name: opnsense-svc
          port: 443
  tls:
    secretName: opnsense-ts-secret
