apiVersion: v1
kind: Service
metadata:
  name: portainer-internal-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 9443
      targetPort: 9443
  selector:
    app: portainer-internal-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-internal-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer-internal-proxy
  template:
    metadata:
      labels:
        app: portainer-internal-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        args: ["TCP-LISTEN:9443,fork", "TCP:192.168.7.40:9443"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            memory: "50Mi"
        ports:
        - containerPort: 9443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-internal-tls-cert
  namespace: external-services
spec:
  secretName: portainer-internal-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "portainer.internal.pimonlab.xyz"
  dnsNames:
  - "portainer.internal.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: portainer-internal-transport
  namespace: external-services
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer-internal-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.internal.pimonlab.xyz`)
      kind: Rule
      services:
        - name: portainer-internal-svc
          port: 9443
          scheme: https 
          serversTransport: portainer-internal-transport
  tls:
    secretName: portainer-internal-ts-secret
