apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-proxy
  template:
    metadata:
      labels:
        app: prometheus-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        args: ["TCP-LISTEN:9090,fork", "TCP:192.168.6.15:9090"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            memory: "50Mi"
        ports:
        - containerPort: 9090
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls-cert
  namespace: external-services
spec:
  secretName: prometheus-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "prometheus.pimonlab.xyz"
  dnsNames:
  - "prometheus.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.pimonlab.xyz`)
      kind: Rule
      services:
        - name: prometheus-svc
          port: 9090
  tls:
    secretName: prometheus-ts-secret
