apiVersion: v1
kind: Service
metadata:
  name: prowlarr-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 9696
      targetPort: 9696
  selector:
    app: prowlarr-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr-proxy
  template:
    metadata:
      labels:
        app: prowlarr-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        args: ["TCP-LISTEN:9696,fork", "TCP:192.168.7.40:9696"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            memory: "50Mi"
        ports:
        - containerPort: 9696
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-tls-cert
  namespace: external-services
spec:
  secretName: prowlarr-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "prowlarr.pimonlab.xyz"
  dnsNames:
  - "prowlarr.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.pimonlab.xyz`)
      kind: Rule
      services:
        - name: prowlarr-svc
          port: 9696
  tls:
    secretName: prowlarr-ts-secret
