apiVersion: v1
kind: Service
metadata:
  name: qbit-2-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: qbit-2-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbit-2-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbit-2-proxy
  template:
    metadata:
      labels:
        app: qbit-2-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        # Listen on 8080 inside the pod, forward to 192.168.3.2:8080
        args: ["TCP-LISTEN:8080,fork", "TCP:192.168.3.2:8080"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            cpu: "10m"
            memory: "50Mi"
        ports:
        - containerPort: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbit-2-tls-cert
  namespace: external-services
spec:
  secretName: qbit-2-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "qbit-2.pimonlab.xyz"
  dnsNames:
  - "qbit-2.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbit-2-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbit-2.pimonlab.xyz`)
      kind: Rule
      services:
        - name: qbit-2-svc
          port: 8080
  tls:
    secretName: qbit-2-ts-secret