apiVersion: v1
kind: Service
metadata:
  name: readmeabook-svc
  namespace: external-services
spec:
  type: ExternalName
  externalName: "192.168.3.2"
  ports:
    - name: web
      port: 3030
      targetPort: 3030
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readmeabook-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readmeabook-proxy
  template:
    metadata:
      labels:
        app: readmeabook-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        # Listen on 3030 inside the pod, forward to 192.168.3.2:3030
        args: ["TCP-LISTEN:3030,fork", "TCP:192.168.3.2:3030"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            cpu: "10m"
            memory: "50Mi"
        ports:
        - containerPort: 3030
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: readmeabook-tls-cert
  namespace: external-services
spec:
  secretName: readmeabook-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "readmeabook.pimonlab.xyz"
  dnsNames:
  - "readmeabook.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: readmeabook-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`readmeabook.pimonlab.xyz`)
      kind: Rule
      services:
        - name: readmeabook-svc
          port: 3030
  tls:
    secretName: readmeabook-ts-secret