apiVersion: v1
kind: Service
metadata:
  name: truenas-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app: truenas-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenas-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truenas-proxy
  template:
    metadata:
      labels:
        app: truenas-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        args: ["TCP-LISTEN:80,fork", "TCP:192.168.2.2:80"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            memory: "50Mi"
        ports:
        - containerPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas-tls-cert
  namespace: external-services
spec:
  secretName: truenas-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "truenas.pimonlab.xyz"
  dnsNames:
  - "truenas.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`truenas.pimonlab.xyz`)
      kind: Rule
      services:
        - name: truenas-svc
          port: 80
  tls:
    secretName: truenas-ts-secret
