apiVersion: v1
kind: Service
metadata:
  name: wgdash-svc
  namespace: external-services
spec:
  ports:
    - name: web
      port: 10086
      targetPort: 10086
  selector:
    app: wgdash-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wgdash-proxy
  namespace: external-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wgdash-proxy
  template:
    metadata:
      labels:
        app: wgdash-proxy
    spec:
      containers:
      - name: socat
        image: alpine/socat
        args: ["TCP-LISTEN:10086,fork", "TCP:192.168.4.2:10086"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            memory: "50Mi"
        ports:
        - containerPort: 10086
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wgdash-tls-cert
  namespace: external-services
spec:
  secretName: wgdash-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "wgdash.pimonlab.xyz"
  dnsNames:
  - "wgdash.pimonlab.xyz"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wgdash-ingress
  namespace: external-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wgdash.pimonlab.xyz`)
      kind: Rule
      services:
        - name: wgdash-svc
          port: 10086
  tls:
    secretName: wgdash-ts-secret
