apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actual-budget-1-tls-cert
  namespace: actual-budget-1
spec:
  secretName: actual-budget-1-ts-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "actual-budget.pimonlab.xyz"
  dnsNames:
  - "actual-budget.pimonlab.xyz"
