apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-1-data-pvc
  namespace: actual-budget-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 5Gi
