---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-selfcloud-nfs-secret
  namespace: kube-system
spec:
  encryptedData:
    driver-config-file.yaml: AgDZgaNZxrlxpek8tNhsIVrrBoYNdR9TAV65+5fpjMe6BARloQnptJqLvXgovsX6uo5tFLqWmnNNaY0digoDazs6bRPK+WYymXL/+XBKHsSiIDO2siEO+PkMAawFfrJTlXvQDhGxsA/tPlqlodJszDvW26UiggkSlPBIomRHuN3UYBqJ3GM6PyklhJ6hePdjYhndRH4kHtDbZZMcF57mDjrw+s3/uycAKx0aYefv7GI2bZmTG9moNRDJBVDXtj3HCl7POWKr3K/Is8U/ugklwdbWgcRR3sbiIV7LOa22QGYoIgeYnvaRy1askLjbvtMffGVwXbhJ+s1RNhQTCYnkp1t7GNNc6CSslHK4onM00I8cB8F1HXMXEuhlHAjrs3kwhspgw5Qah0nAwUtX09iSc8jHDzKQ8Gnhx7D+yylD7ts3I3kyIfersduK6JTPQMfnWhNSxqrKGg1QUOz2VdoasKl+D4Gt5WdLTztd7TASdPgcNzQZ6FlFTwLKTlbzoubJcz2lCL/R//T2m7xN8u69s1OQaBXyfU6cUw3bVP3oFiidPARkBDCW60Fx8vAN2k3QthaGgBvc3QAYNg/7cUCDq/uU8PRAuHK8/FuWF4c+WBBEia+hyvojWCIE7CVXFQnIY7k32uifFJxaJKpEwbPN+7fSpCukr+84IQDh9pi5AuZNPVo9jYqLDukpQCMfBwjQjJI3ZoOVashVOJs+qPqOz+2zBFbhwDK2xXtXewHUa1BcbQL6UFsAzfLzCYMZ9nGTOx5Ap4tOvQ/fsMVN1u3PF2seQ6iAiTe61OAADhjvCPpbWpQ2GtKD7uZNG89YfYNN0VicnzTiUwDLrfGEu5DZTGMErWfB0Ip8KC+PnEbSQ7QokR22v+oWvRC4rgVnDknVRSizzt8Fy66YNGJcbTJqUpJr0K7sobn8RcZSACSGx8AYy2jNxVVl6i7ggwgcnMhwOjChm/ultqNjreFmjxFD0aM2TrPAIH90T4Rp0PCRsacak2Skhg58B/eq55y6TmKjXQ80FmRTsys0azacM+Jtd8stKcvswv4345A+evuyGuQr8RcY57Rpv4fFFKW+gaWeLxy4AuZAA3gIDepTvPP4Ht6Ufw0c63O1RZDZNJHOfio3NhPkOUAc4z1eNdu4E9/DpWWn7DmPgAcNkP22Pai0KgFdkpWU8WeN7gJgEaF+KlNCitPRgYerjZ5lGhlsFpGF2OPhYY8xv4H3tq5Fnt+NkpJuoZ2tZM3iNnkmxhK6/wtZ+3Q6zMIkyNn4bnW1FMGCCPNCRjwY+aiEiRZaIqEweov+AHw8xcqRAvj94HZ78IfYUFFoGvuPNzFs7LiX/D8Y+e/9SHBkaFTJL7wsXHuV5HsS5bEIn75K
  template:
    metadata:
      name: truenas-selfcloud-nfs-secret
      namespace: kube-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-selfcloud-iscsi-secret
  namespace: kube-system
spec:
  encryptedData:
    driver-config-file.yaml: AgAiZqn/CKZva+qIxmeX6UEUUZrw64QCF4YMWd6dbYD5f3BTDf8mebqYcPM0fha9Ta6Fng6j7NXml/WTqpvU0OjBELeu52sG5nlRsxmolt9GHT8BSf1ft7ZGSzUCgGPJWZpyRDLhXlfozc5Zvxywi1BYJy72el4JUUZCW18Epls4xKbtgiRQDphn2YfNfEz+0FoqFh00qWQKW9XyqjoFQ4dKziTPOwUhUX8u3Znt23Irg3AWsc3v7bnfVtFaW+fxzOW6GV77UiqDZi3+lyNKnPDnPlxYWbkX6L+Cb/wl6iLFstCoE3Q++aeO2WGhfAC9SRyzJus6gF0evc2UI/wsvG+H/De0hZdj+SYOwsXpnZVKcoDrMiTmd8gdaSjBE81FeZsB57S0uMwgETma4ji4RckKUEGqEmKGgBiluXU5Zyc5uaBHHwz31580XR5ddVX/MVmC32MOps+agAhGyp9KygW/RrqsCk0bKHi2AHsobCicuzV8JM8/yk0H+n/icQQ95/Y1c5od1DqOfX/guRi5o45i1iqtxfy9jz+gI0xd5sFPrW+ka0V5QH8LUXEvCjcBdUvqvj4e0SreNYPCXcGboVr2/bip9OBzToIRWIAzhGzyFfh5cnUJwJpifmK92IUyGs/asytGVqGway0M0ImCL5pwa/hLvazr/oBrwfY34Uf+HrcSk10JlB960zBDxJHEVIYLbiycF54+MHNd55U62GU4W1Qomptj4cdczBGZQL3e+a9P4IzPKd81+te56paBxNxy46xcxgSQn50eE+JY+AwJh4wCeWBNmzcYtSybRC3IABvL1OFt/sdyF/XMIt9bygYAU+6AtS+nnkc1AHbaqhtm6Yxyzl4e60EAJq4UfxQwtKBROV32FeCbzOP2KzDSZkQbaZ1r0awZHXbD+L2cAfJjNbfW+3adHZaybnaElKJS0vy48r/Zd/y2okf6kxYZHCnTrlkLW+5B4Wga9/3bTwqmfd5kwj+7MuyIkVpYvg746d9DcuPRiinG+F3i4uh0+LoKxNs1HJ+i2xcMqR/tUKhEsA4TayCC08V/nEsm3vCEBzrcO6becAZTu9wA7SXfbHGT1kuqJgvOHQwIiCVQYA8EHxD1e8f/4MPdzsQe4DLDIJaYXZYXOTZpC9/hMIlBRZRnUzQIArRgmnUlyTrFJhYceEZWPWz3m9brtVlZg8YiQoWqmtceyGmE9ry8kZlqGdnraP/6FDHvc3whG3gA2lMRwK22HjE064M46ZY8drOqp2kIUjQvxFS4c2+udnXhIP5o5+uYHN95l4neJFGXLWqA09W543wCE/H6ioWiyhBWrN/CmxquEhlynVOoSv/clNx/NKlOD5532UvKRXmJ1z29oZ2MkJqMG6YDIO0CoLi/6xZ88U9OkfCaYBUXw8Uft5yP/GzH3vi7FPuAyygQeu4PQIYvTtGpir7JSsoYLwDGB2OJXTkA6cQ=
  template:
    metadata:
      name: truenas-selfcloud-iscsi-secret
      namespace: kube-system
    type: Opaque
